const BlobSetting = [
  {
    material: {
      roughness: 0.44,
      metalness: 0.73,
      envMapIntensity: 0.95,
      clearcoat: 0.13,
      clearcoatRoughness: 1.0,
      transmission: 1.0,
      color: "#ffffff",
      distort: 0.08,
      frequency: 2.77,
      speed: 1.0,
      gooPoleAmount: 1,
      surfaceDistort: 3.6,
      surfaceFrequency: 1.62,
      numberOfWaves: 3.4,
      surfaceSpeed: 1,
      surfacePoleAmount: 1,
    },
    light: [
      {
        position: [3.87, -3.73, 1.93],
        intensity: 5.0,
        angle: 0.22,
        distance: 20.0,
        penumbra: 1.0,
        decay: 0.0,
        color: "#000FFF",
      },
      {
        position: [-2.8, -6.67, 5.73],
        intensity: 0.7,
        angle: 0.31,
        distance: 9.53,
        penumbra: 1.0,
        decay: 0.0,
        color: "#FFFF00",
      },
      {
        position: [1.33, -0.27, 7.93],
        intensity: 5.0,
        angle: 1.57,
        distance: 8.2,
        penumbra: 1.0,
        decay: 0.0,
        color: "#7600FF",
      },
    ],
    bg: "#75BCC6",
  },
  {
    material: {
      roughness: 0.14,
      metalness: 0.0,
      envMapIntensity: 1.0,
      clearcoat: 1.0,
      clearcoatRoughness: 0.7,
      transmission: 0.0,
      color: "#ffffff",
      distort: 0.5,
      frequency: 1.5,
      speed: 1.0,
      gooPoleAmount: 1,
      surfaceDistort: 1.0,
      surfaceFrequency: 1.0,
      numberOfWaves: 4.0,
      surfaceSpeed: 1,
      surfacePoleAmount: 1,
    },
    light: [
      {
        position: [3.87, -3.73, 1.93],
        intensity: 5.0,
        angle: 0.22,
        distance: 20.0,
        penumbra: 1.0,
        decay: 0.0,
        color: "#000FFF",
      },
      {
        position: [-2.8, -6.67, 5.73],
        intensity: 0.7,
        angle: 0.31,
        distance: 9.53,
        penumbra: 1.0,
        decay: 0.0,
        color: "#FFFF00",
      },
      {
        position: [1.33, -0.27, 7.93],
        intensity: 5.0,
        angle: 1.57,
        distance: 8.2,
        penumbra: 1.0,
        decay: 0.0,
        color: "#7600FF",
      },
    ],
    bg: "#657174",
  },
];

export default BlobSetting;
