import { Vector3 } from "three";
import { SettingType } from "./settingType";

const BlobSetting: SettingType[] = [
  {
    material: {
      roughness: 0.44,
      metalness: 0.73,
      envMapIntensity: 0.95,
      clearcoat: 0.13,
      clearcoatRoughness: 1.0,
      transmission: 1.0,
      color: "#ffffff",
      distort: 0.08,
      frequency: 2.77,
      speed: 1.0,
      gooPoleAmount: 1,
      surfaceDistort: 3.6,
      surfaceFrequency: 1.62,
      numberOfWaves: 3.4,
      surfaceSpeed: 1,
      surfacePoleAmount: 1,
    },
    lights: [
      {
        position: new Vector3(3.87, -3.73, 1.93),
        intensity: 5.0,
        angle: 0.22,
        distance: 20.0,
        penumbra: 1.0,
        decay: 0.0,
        color: "#000FFF",
      },
      {
        position: new Vector3(-2.8, -6.67, 5.73),
        intensity: 0.7,
        angle: 0.31,
        distance: 9.53,
        penumbra: 1.0,
        decay: 0.0,
        color: "#FFFF00",
      },
      {
        position: new Vector3(1.33, -0.27, 7.93),
        intensity: 5.0,
        angle: 1.57,
        distance: 8.2,
        penumbra: 1.0,
        decay: 0.0,
        color: "#7600FF",
      },
    ],
    bg: "#75BCC6",
    map: "iridescent",
  },
  {
    material: {
      roughness: 0.0,
      metalness: 0.0,
      envMapIntensity: 0.05,
      clearcoat: 1.0,
      clearcoatRoughness: 0.14,
      transmission: 0.0,
      color: "#ffffff",
      distort: 0.0,
      frequency: 0.06,
      speed: 2.0,
      gooPoleAmount: 1,
      surfaceDistort: 3.1,
      surfaceFrequency: 0.28,
      numberOfWaves: 1.0,
      surfaceSpeed: 1,
      surfacePoleAmount: 1,
    },
    lights: [
      {
        position: new Vector3(-5.0, 0.07, 1.93),
        intensity: 1.27,
        angle: 0.42,
        distance: 8.27,
        penumbra: 1.0,
        decay: 1.0,
        color: "#00FFF8",
      },
      {
        position: new Vector3(-2.73, -6.67, 5.73),
        intensity: 3.0,
        angle: 0.52,
        distance: 9.53,
        penumbra: 1.0,
        decay: 0.5,
        color: "#7800FF",
      },
      {
        position: new Vector3(1.2, 2.67, 4.6),
        intensity: 2.0,
        angle: 0.39,
        distance: 8.2,
        penumbra: 1.0,
        decay: 0.5,
        color: "#FFFFFF",
      },
    ],
    bg: "#7600F0",
    map: "rainbow",
  },
  {
    material: {
      roughness: 0.0,
      metalness: 0.0,
      envMapIntensity: 0.05,
      clearcoat: 1.0,
      clearcoatRoughness: 0.14,
      transmission: 0.0,
      color: "#ffffff",
      distort: 0.0,
      frequency: 0.06,
      speed: 2.0,
      gooPoleAmount: 1,
      surfaceDistort: 3.1,
      surfaceFrequency: 0.28,
      numberOfWaves: 1.0,
      surfaceSpeed: 1,
      surfacePoleAmount: 1,
    },
    lights: [
      {
        position: new Vector3(-5.0, 0.07, 1.93),
        intensity: 1.27,
        angle: 0.42,
        distance: 8.27,
        penumbra: 1.0,
        decay: 1.0,
        color: "#00FFF8",
      },
      {
        position: new Vector3(-2.73, -6.67, 5.73),
        intensity: 3.0,
        angle: 0.52,
        distance: 9.53,
        penumbra: 1.0,
        decay: 0.5,
        color: "#7800FF",
      },
      {
        position: new Vector3(1.2, 2.67, 4.6),
        intensity: 2.0,
        angle: 0.39,
        distance: 8.2,
        penumbra: 1.0,
        decay: 0.5,
        color: "#FFFFFF",
      },
    ],
    bg: "#7600F0",
    map: "foil",
  },
];

export default BlobSetting;
